language: php

php:
  - 5.3

before_script:
  - mkdir -p /tmp/plugins/sitemap
  - mv * /tmp/plugins/sitemap
  - mkdir /tmp/ls && git clone git://github.com/stfalcon-studio/livestreet.git /tmp/ls
  - cp -a /tmp/ls/* ./
  - mkdir -p plugins/sitemap && cp -a /tmp/plugins/sitemap/* plugins/sitemap
  - ls -la 
  - echo "sitemap" > ./plugins/plugins.dat

  # change application working folders for write access
  - chmod -R 0777 ./tmp
  - chmod -R 0777 ./uploads
  - chmod -R 0777 ./templates/cache/
  - chmod -R 0777 ./templates/compiled/

  # install required PHP stuff
  - sudo apt-get install php5 php5-cli php5-mysql php5-mcrypt php5-xsl php5-xdebug php-apc php5-gd php5-curl php5-intl

  # launch apache, MySQL and PHPUnit Selenium installers
  - ./tests/travis/apache_setup.sh
  - ./tests/travis/mysql_setup.sh
  - mysql -u root -e "USE social_test; SHOW TABLES;" | wc -l
  - cp ./config/config.test.php.dist config/config.test.php
  - cp ./config/config.test.php.dist config/config.local.php
  - sudo sed -i s/sql-mode/#sql-mode/ /etc/mysql/my.cnf
  - sudo /etc/init.d/mysql restart
  - sleep 5

  - wget -S http://livestreet.test
  - rm -rf ./install


script: HTTP_APP_ENV=test php tests/behat/behat.phar -c tests/behat/behat.yml
