language: php

php:
  - 5.3

before_script:
  - mkdir -p plugins/sitemap
  - mv * plugins/sitemap
  - git clone git://github.com/stfalcon-studio/livestreet.git
  - rm -rf ./install
  - ls -l 

  # change application working folders for write access
  - chmod -R 0777 ./tmp
  - chmod -R 0777 ./uploads
  - chmod -R 0777 ./templates/cache/
  - chmod -R 0777 ./templates/compiled/

  # install required PHP stuff
  - sudo apt-get install php5 php5-cli php5-mysql php5-mcrypt php5-xsl php5-xdebug php-apc php5-gd php5-curl php5-intl

  # launch apache, MySQL and PHPUnit Selenium installers
  - cp ./config/config.test.php.dist config/config.test.php
  - cp ./config/config.test.php.dist config/config.local.php
  - sudo sed -i s/sql-mode/#sql-mode/ /etc/mysql/my.cnf
  - sudo /etc/init.d/mysql restart
  - sleep 5

  - wget -S http://livestreet.test


script: HTTP_APP_ENV=test php tests/behat/behat.phar -c tests/behat/behat.yml
